input {
    kafka {
        bootstrap_servers => "localhost:9092"
        topics => ["kafka-logs-1"]
    }
}
filter {
    grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
    }
}

output {
    elasticsearch {
        hosts => ["http://localhost:9200"]
        index => "kafka-logs"
    }
    stdout { codec => rubydebug }
}